services:
  backend:
    build:
      context: ./server-app/
      dockerfile: ServerApp/Dockerfile
    ports:
      - "5219:5219"
      - "7045:7045"
    environment:    
      - ConnectionStrings__MainDatabase=Host=database;Port=5432;Database=${DB_NAME};Username=${DB_USERNAME};Password=${DB_PASSWORD};
      - ASPNETCORE_URLS=http://+:5219
    depends_on:
      - database
  
  client-web-app:
    build:
      context: ./client-app/
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_APP_PORT}:8080
    depends_on:
      - backend 
  
  database:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - backend-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  backend-db-volume:
